{
 "title": "Aeternity P2P Monitor - Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "networkId", "label": "Network", "query": { "query": "label_values(networkId)" } }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_network_difficulty{networkId=\"$networkId\"}",
     "legendFormat": "{{genesisHash}}"
    }
   ]
  },
  {
   "title": "Genesis Hash",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_network_difficulty{networkId=\"$networkId\"}",
     "legendFormat": "{{genesisHash}}"
    }
   ]
  },
  {
   "title": "Network Peers",
   "type": "stat",
   "description": "Total unique peers seen in the network in MSG_PING messages.",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_network_peers{networkId=\"$networkId\"}",
     "legendFormat": "unique"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_network_difficulty{networkId=\"$networkId\"}",
     "legendFormat": "{{networkId}}"
    }
   ]
  },
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Node Peers",
   "type": "timeseries",
   "description": "Average node peers as reported by MSG_NODE_INFO message.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(aemon_node_peers{networkId=\"$networkId\"}) by (kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Difficulty",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(aemon_peer_difficulty[$__interval]))",
     "legendFormat": "difficulty"
    }
   ]
  },
  {
   "title": "Difficulty Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"diff\", aemon_peer_difficulty{networkId=\"$networkId\"})",
     "legendFormat": "{{diff}}"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aemon_peer_info{networkId=\"$networkId\"}) by (version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operating System",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aemon_peer_info{networkId=\"$networkId\"}) by (os)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Geo Locations",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aemon_peer_status{networkId=\"$networkId\", lat != \"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revisions",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aemon_peer_info{networkId=\"$networkId\"}) by (revision)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vendor",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aemon_peer_info{networkId=\"$networkId\"}) by (vendor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer List",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "aemon_peer_info{networkId=\"$networkId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Sent Messages by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(aemon_messages_total{networkId=\"$networkId\", direction=\"sent\"}[$__interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Messages by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(aemon_messages_total{networkId=\"$networkId\", direction=\"received\"}[$__interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Responses by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(increase(aemon_responses_total{networkId=\"$networkId\", direction=\"received\"}[$__interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Responses by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(increase(aemon_responses_total{networkId=\"$networkId\", direction=\"sent\"}[$__interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Connections by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum(increase(aemon_connections_total{networkId=\"$networkId\"}[$__interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "aemon_connections{networkId=\"$networkId\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Connection errors by code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum(increase(aemon_connection_errors_total{networkId=\"$networkId\"}[20s])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}