{
 "title": "Aeternity P2P Monitor - Messages",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "networkId", "label": "Network", "query": { "query": "label_values(networkId)" } }
  ]
 },
 "panels": [
  {
   "title": "Sent Messages (m/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(aemon_messages_total{networkId=\"$networkId\", direction=\"sent\"}[$__interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Responses (r/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(aemon_responses_total{networkId=\"$networkId\", direction=\"received\"}[$__interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gossip Messages (m/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(aemon_messages_total{networkId=\"$networkId\", direction=\"received\", type!=\"response\"}[$__interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Responses (r/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(aemon_responses_total{networkId=\"$networkId\", direction=\"sent\"}[$__interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}