{
 "title": "Aeternity P2P Monitor - Peer",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "publicKey",
    "label": "Peer",
    "query": {
     "query": "label_values(aemon_peer_status, publicKey)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(aemon_peer_status{publicKey=\"$publicKey\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status History",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "aemon_peer_status{publicKey=\"$publicKey\"}",
     "legendFormat": "{{host}}:{{port}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_peer_info{publicKey=\"$publicKey\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_peer_info{publicKey=\"$publicKey\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_peer_status{publicKey=\"$publicKey\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_peer_status{publicKey=\"$publicKey\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vendor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_peer_info{publicKey=\"$publicKey\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_peer_info{publicKey=\"$publicKey\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current Difficulty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_peer_difficulty{publicKey=\"$publicKey\"}",
     "legendFormat": "difficulty"
    }
   ]
  },
  {
   "title": "Network ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_peer_status{publicKey=\"$publicKey\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Genesis Hash",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_peer_difficulty{publicKey=\"$publicKey\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aemon_peer_difficulty{publicKey=\"$publicKey\"}",
     "legendFormat": "difficulty"
    }
   ]
  },
  {
   "title": "Node Peers",
   "type": "timeseries",
   "description": "Average node peers as reported by MSG_NODE_INFO message.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (kind) (aemon_node_peers{publicKey=\"$publicKey\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "aemon_peer_status{publicKey=\"$publicKey\", lat!=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}