{
 "title": "Aeternity P2P Monitor - Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "networkId", "label": "Network", "query": { "query": "label_values(networkId)" } }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_network_difficulty{networkId=\"$networkId\"}",
     "legendFormat": "{{genesisHash}}"
    }
   ]
  },
  {
   "title": "Genesis Hash",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aemon_network_difficulty{networkId=\"$networkId\"}",
     "legendFormat": "{{genesisHash}}"
    }
   ]
  },
  {
   "title": "Gossip Peers",
   "type": "stat",
   "description": "Total unique peers seen in the network in MSG_PING messages.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aemon_network_peers{networkId=\"$networkId\"})",
     "legendFormat": "unique peers"
    }
   ]
  },
  {
   "title": "Average Node Peers",
   "type": "timeseries",
   "description": "Average node peers as reported by MSG_NODE_INFO message.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(aemon_node_peers{networkId=\"$networkId\"}) by (kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Height",
   "type": "stat",
   "description": "Observed in gossip network in keyblocks",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aemon_network_height{networkId=\"$networkId\"})",
     "legendFormat": "{{networkId}}"
    }
   ]
  },
  {
   "title": "Max Difficulty",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aemon_network_difficulty{networkId=\"$networkId\"})",
     "legendFormat": "{{networkId}}"
    }
   ]
  },
  {
   "title": "Ping Latency (95th)",
   "type": "stat",
   "description": "Ping latency 95th percentile",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(aemon_peer_latency_seconds_bucket{networkId=\"$networkId\"}[$__interval])) by (le))",
     "legendFormat": "unique"
    }
   ]
  },
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Versions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7, count(aemon_peer_info{networkId=\"$networkId\"}) by (version))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Difficulty Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"diff\", aemon_peer_difficulty{networkId=\"$networkId\"})",
     "legendFormat": "{{diff}}"
    }
   ]
  },
  {
   "title": "Average Difficulty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(aemon_peer_difficulty{networkId=\"$networkId\"}[$__interval]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Max Deviation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(stddev_over_time(aemon_peer_difficulty{networkId=\"$networkId\"}[$__interval]))",
     "legendFormat": "deviation"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Gossip Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(aemon_messages_total{networkId=\"$networkId\", direction=\"received\", type!=\"response\"}[$__interval]))",
     "legendFormat": "m/sec"
    }
   ]
  },
  {
   "title": "Gossip Messages by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum_over_time(aemon_messages_total{networkId=\"$networkId\", direction=\"received\", type!=\"response\"}[$__interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg(aemon_connections{networkId=\"$networkId\"}) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Inbound Connection Errors",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(aemon_connection_errors_total{networkId=\"$networkId\", direction=\"inbound\"}[1m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Connection Errors",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum_over_time(aemon_connection_errors_total{networkId=\"$networkId\", direction=\"outbound\"}[$__range])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Inbound Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(aemon_connections_total{networkId=\"$networkId\", direction=\"inbound\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Outbound Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(aemon_connections_total{networkId=\"$networkId\", direction=\"outbound\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}