{
 "title": "Aeternity P2P Monitor - Peers",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "networkId", "label": "Network", "query": { "query": "label_values(networkId)" } }
  ]
 },
 "panels": [
  {
   "title": "Top Versions",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7, count(aemon_peer_info{networkId=\"$networkId\"}) by (version))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Revisions",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7, count(aemon_peer_info{networkId=\"$networkId\"}) by (revision))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vendors",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aemon_peer_info{networkId=\"$networkId\"}) by (vendor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operating Systems",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aemon_peer_info{networkId=\"$networkId\"}) by (os)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Countries",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7, count(aemon_peer_status{networkId=\"$networkId\"}) by (country))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top  Providers",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7, count(aemon_peer_status{networkId=\"$networkId\"}) by (provider))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer List",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "aemon_peer_status{networkId=\"$networkId\"} * on (instance, publicKey) group_left(version, revision, vendor, os) aemon_peer_info{networkId=\"$networkId\"} or on (instance, publicKey) aemon_peer_status{networkId=\"$networkId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Geo Locations",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(__name__, Time, instance, job, country, networkId) (aemon_peer_status{networkId=\"$networkId\", lat != \"0\", kind=\"seed\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum without(instance, __name__, Time, job, country, networkId) (aemon_peer_status{networkId=\"$networkId\", lat!=\"0\", kind!=\"seed\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}