{
 "title": "Aeternity P2P Monitor - Speed",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "networkId", "label": "Network", "query": { "query": "label_values(networkId)" } }
  ]
 },
 "panels": [
  {
   "title": "Network Throughput",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(aemon_peer_throughput_bytes_bucket{networkId=\"$networkId\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Network Throughput Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(aemon_peer_throughput_bytes_bucket{networkId=\"$networkId\"}[5m])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(aemon_peer_throughput_bytes_bucket{networkId=\"$networkId\"}[5m])) by (le))",
     "legendFormat": "95th"
    }
   ]
  },
  {
   "title": "Ping Latency (packets/s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(aemon_peer_latency_seconds_bucket{networkId=\"$networkId\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Ping Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(aemon_peer_latency_seconds_bucket{networkId=\"$networkId\"}[5m])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(aemon_peer_latency_seconds_bucket{networkId=\"$networkId\"}[5m])) by (le))",
     "legendFormat": "95th"
    }
   ]
  },
  {
   "title": "Key Block Latency (blocks/s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(aemon_block_latency_seconds_bucket{networkId=\"$networkId\", type=\"key\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Key Block Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  avg(rate(aemon_block_latency_seconds_sum{networkId=\"$networkId\", type=\"key\"}[10m])/rate(aemon_block_latency_seconds_count{networkId=\"$networkId\", type=\"key\"}[10m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(aemon_block_latency_seconds_bucket{networkId=\"$networkId\", type=\"key\"}[10m])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(aemon_block_latency_seconds_bucket{networkId=\"$networkId\", type=\"key\"}[10m])) by (le))",
     "legendFormat": "95th"
    }
   ]
  },
  {
   "title": "Micro Block Latency (blocks/s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(aemon_block_latency_seconds_bucket{networkId=\"$networkId\", type=\"micro\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Micro Block Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  avg(rate(aemon_block_latency_seconds_sum{networkId=\"$networkId\", type=\"micro\"}[5m])/rate(aemon_block_latency_seconds_count{networkId=\"$networkId\", type=\"micro\"}[5m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(aemon_block_latency_seconds_bucket{networkId=\"$networkId\", type=\"micro\"}[5m])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(aemon_block_latency_seconds_bucket{networkId=\"$networkId\", type=\"micro\"}[5m])) by (le))",
     "legendFormat": "95th"
    }
   ]
  }
 ]
}