name: Mainline

on:
  push:
    branches: [ master ]

jobs:
  validate:
    uses: aeternity/github-actions/.github/workflows/_validate-npm.yml@v1.2.0
  publish:
    uses: aeternity/github-actions/.github/workflows/_publish-docker.yml@v1.2.0
    needs: [ validate ]
    secrets: inherit
  deploy:
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v1.2.0
    needs: [publish]
    secrets: inherit
    strategy:
      max-parallel: 1
      matrix:
        env: [dev, stg]
        flavor: [testnet, mainnet]
    with:
      DEPLOY_ENV: ${{ matrix.env }}
      DEPLOY_APP: "${{ github.event.repository.name }}-${{ matrix.flavor }}"
      DEPLOY_VERSION: master
      DEPLOY_HOST_PREFIX: ""
