name: Publish Artifacts

on:
  workflow_run:
    workflows: ["Validate"]
    types: [completed]
    # branches: [ master ]
    # tags: [ v* ]

jobs:
  dockerhub:
    name: "Publish to Dockehub"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.GITHUB_REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=semver,pattern=v{{version}}

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        if: ${{ steps.meta.outputs.tags }}
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
