name: "Pull Request"

on:
  pull_request:
    branches: [ master ]

jobs:
  validate:
    uses: aeternity/github-actions/.github/workflows/_validate-npm.yml@v1.0.0
  publish:
    uses: aeternity/github-actions/.github/workflows/_publish-docker.yml@v1.0.0
    needs: [ validate ]
    secrets: inherit
    with:
      DOCKERHUB_REPO: aeternitybot/aemon
