name: "Pull Request"

on:
  pull_request:
    branches: [ master ]

jobs:
  validate:
    uses: aeternity/github-actions/.github/workflows/_validate-npm.yml@v2.3.1
  publish:
    uses: aeternity/github-actions/.github/workflows/_publish-ecr.yml@v2.3.1
    needs: [ validate ]
    secrets: inherit
