name: "Pull Request Cleanup"

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  delete-tag:
    uses: aeternity/github-actions/.github/workflows/_delete-tag-ecr.yml@v2.3.1
    secrets: inherit
    with:
      TAG: "pr-${{ github.event.number }}"
  cleanup:
    uses: aeternity/github-actions/.github/workflows/_cleanup-ecr.yml@v2.3.1
    needs: [ delete-tag ]
    secrets: inherit
