name: "Pull Request Cleanup"

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

env:
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}

jobs:
  delete-tag:
    uses: aeternity/github-actions/.github/workflows/_delete-tag-docker.yml@v1.0.0
    secrets: inherit
    with:
      DOCKERHUB_REPO: ${{ env.DOCKERHUB_REPO }}
      DOCKERHUB_TAG: "pr-${{ github.event.number }}"
