name: "Pull Request"

on:
  pull_request:
    branches: [ master ]

env:
  GH_WORKFLOWS: aeternity/github-actions/.github/workflows

jobs:
  validate:
    uses: aeternity/github-actions/.github/workflows/_validate-npm.yml@master
  publish:
    uses: aeternity/github-actions/.github/workflows/_publish.yml@master
    needs: [ validate ]
    secrets: inherit
