name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  validate:
    uses: ./.github/workflows/_validate.yml
  publish:
    uses: ./.github/workflows/_publish.yml
    needs: [ validate ]
    secrets: inherit
