name: "Pull Request"

on:
  pull_request:
    branches: [ master ]

jobs:
  validate:
    uses: aeternity/github-actions/.github/workflows/_validate-npm.yml@master
  publish:
    uses: aeternity/github-actions/.github/workflows/_publish-docker.yml@master
    needs: [ validate ]
    secrets: inherit
