name: "Pull Request"

on:
  pull_request:
    branches: [ master ]

env:
  GH_WORKFLOWS: aeternity/github-actions/.github/workflows

jobs:
  validate:
    uses: ${{ env.GH_WORKFLOWS }}/_validate-npm.yml@master
  publish:
    uses: ${{ env.GH_WORKFLOWS }}/_publish-docker.yml@master
    needs: [ validate ]
    secrets: inherit
