name: Release

on:
  push:
    tags: [ v* ]

jobs:
  validate:
    uses: aeternity/github-actions/.github/workflows/_validate-npm.yml@v2.3.1
  publish:
    uses: aeternity/github-actions/.github/workflows/_publish-ecr.yml@v2.3.1
    needs: [ validate ]
    secrets: inherit
  deploy:
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.3.1
    needs: [publish]
    secrets: inherit
    strategy:
      max-parallel: 1
      matrix:
        flavor: [testnet, mainnet]
    with:
      DEPLOY_ENV: prd
      DEPLOY_APP: "${{ github.event.repository.name }}-${{ matrix.flavor }}"
      DEPLOY_TAG: ${{ github.ref_name }}
